### PR TITLE
Prac 07 feedback

### PR DESCRIPTION
**Pull request by jacklly**
@EricaFinlay didn't get to finish this weeks sadly

### CODE REVIEW

**Comment by EricaFinlay** [comment]
Hi
I'm at work and will review it as soon as I finish at 3pm and get home.
I understand you'll need to submit it in the meantime.
Hope that's OK.
Regards,
Erica Finlay

________________________________
From: jacklly ***@***.***>
Sent: Thursday, 10 November 2022 9:49 AM
To: jacklly/Practicals ***@***.***>
Cc: Erica Finlay ***@***.***>; Mention ***@***.***>
Subject: [jacklly/Practicals] Prac 07 feedback (PR #3)


@EricaFinlay<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEricaFinlay&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614468670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZFnRVx04MNpyLnL9ghR3%2BBi2Sw68zijCMzyk%2BmIiWN8%3D&reserved=0> didn't get to finish this weeks sadly

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/jacklly/Practicals/pull/3<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xdn%2BEyWfR%2B%2B%2FjEKHPdi%2Buy09gsS%2FJh8oyhGLb7hgQ1I%3D&reserved=0>

Commit Summary

  *   2c1e8e5<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Fcommits%2F2c1e8e5574c1e3f25c1b4c13a15a973ddb26e0e6&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=THNSIsHTgOYoGg169eG2dai9eYQmGCNbKRnQP7c9pqw%3D&reserved=0> Initial commit
  *   2122756<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Fcommits%2F2122756bed0354f94ee128d3db20844bf0662162&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JqWKMB4JKEvR9tVDcM6W%2B8DCkPGNaeN4fZ%2FO1iM9yBI%3D&reserved=0> Added sorting to guitar.py for myguitars.py
  *   3915534<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Fcommits%2F3915534844a6d8cdd445821ae7d32f687ea6175b&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lH8TcZmtzB6Ae8So0v77HXK4t41PphQ4kRHk7I9z1wo%3D&reserved=0> Completed myguitars.py
  *   f22c670<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Fcommits%2Ff22c67056b43ae0a9b4b98c5c9e68aa196c1c5ec&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0cOKD2kmJpCX1kI6cboeuxFpInFKFrvk0gJsHZJcjK4%3D&reserved=0> refactored into functions

File Changes

(3 files<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Ffiles&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U%2BsrJrpU3SWBIxBeafaUUkssk89d6bTdwjWOSFTIn3A%3D&reserved=0>)

  *   M Prac_06/guitar.py<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Ffiles%23diff-7edd2b2631fbfe795db07f7ccb68ecd4ef143bf6eeb4538606c92d356156a389&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SKDNQCQBpPZDne1MsaD24Rcb1Uk6FGWhHg6xTt8doNQ%3D&reserved=0> (3)
  *   A Prac_07/guitars.csv<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Ffiles%23diff-27c6c9edf4502869c4a2102f9aebda8ba058be01452abc6ab38a53a2580c46b6&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=caT60RSy1fo4h9P%2BJFzbdfQT4BpZiNYhouehzSEuhCo%3D&reserved=0> (8)
  *   A Prac_07/myguitars.py<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3%2Ffiles%23diff-e3797f3480436d98d1c5cc2e0aacbb9091a6ac6e721535e43aafd3897a5ba9e8&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8mvy%2FSdqv4Kg%2BeXfSCExwyfi0knvk1jM3RnkF7rDtV8%3D&reserved=0> (61)

Patch Links:

  *   https://github.com/jacklly/Practicals/pull/3.patch<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3.patch&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=URtQO22Cqipfnm1ptixglfP0zNbf0DYODSaL3ucl51c%3D&reserved=0>
  *   https://github.com/jacklly/Practicals/pull/3.diff<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjacklly%2FPracticals%2Fpull%2F3.diff&data=05%7C01%7Cerica.finlay%40my.jcu.edu.au%7C5506648fe0ee4c35d47f08dac2ad04bf%7C2eba4cf8af764db3bcaf81b5592535ef%7C0%7C0%7C638036345614624883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5%2F4ZJTXF8QZORpgrobKszS%2BwzGIqKCLz8cjSJvtewE8%3D&reserved=0>

**Comment by jacklly** [comment]
all good dude, i aint too stressed

**Review by EricaFinlay — APPROVED** [review]
Hi @jacklly 

Apologies for the delay in doing this review.

The code you've written looks good to me however I just wondered if your name for the list "savable_guitars" could just be simplified to "guitars"?

Hope that's OK.

Regards,
Erica Finlay

**Review by EricaFinlay — COMMENTED** [review]
Hi Jack

Looks good to me though maybe use a capital letter & full stop for the docstring for taxi_test.

Thanks,
Erica Finlay

**Comment by jacklly** [comment]
sorry @EricaFinlay was meant to make a new branch, thats my bad :((

**Comment by EricaFinlay** [comment]
All fine.  I wasn't sure if I was meant to reply or not.

Thanks,
Erica
________________________________

**Pull request merged**
